package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseCashback;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_cashback", primaryKey = "id")
public class Cashback extends BaseCashback<Cashback> {
	public static final String table = "t_cashback";
	public static final Cashback dao = new Cashback().dao();
}
