package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseMarketcodeCodeactiveRcd;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_marketcode_codeactive_rcd", primaryKey = "id")
public class MarketcodeCodeactiveRcd extends BaseMarketcodeCodeactiveRcd<MarketcodeCodeactiveRcd> {
	public static final String table = "t_marketcode_codeactive_rcd";
	public static final MarketcodeCodeactiveRcd dao = new MarketcodeCodeactiveRcd().dao();
}
