package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseMarketcodeCodeactive;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_marketcode_codeactive", primaryKey = "id")
public class MarketcodeCodeactive extends BaseMarketcodeCodeactive<MarketcodeCodeactive> {
	public static final String table = "t_marketcode_codeactive";
	public static final MarketcodeCodeactive dao = new MarketcodeCodeactive().dao();
}
