package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseMarketcodeJifen;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_marketcode_jifen", primaryKey = "id")
public class MarketcodeJifen extends BaseMarketcodeJifen<MarketcodeJifen> {
	public static final String table = "t_marketcode_jifen";
	public static final MarketcodeJifen dao = new MarketcodeJifen().dao();
}
