package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFullCutSet<M extends BaseFullCutSet<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setFullCutId(java.lang.Long fullCutId) {
		set("full_cut_id", fullCutId);
		return (M)this;
	}
	
	public java.lang.Long getFullCutId() {
		return getLong("full_cut_id");
	}

	public M setMeet(java.math.BigDecimal meet) {
		set("meet", meet);
		return (M)this;
	}
	
	public java.math.BigDecimal getMeet() {
		return get("meet");
	}

	public M setCashRequired(java.lang.Integer cashRequired) {
		set("cash_required", cashRequired);
		return (M)this;
	}
	
	public java.lang.Integer getCashRequired() {
		return getInt("cash_required");
	}

	public M setCash(java.math.BigDecimal cash) {
		set("cash", cash);
		return (M)this;
	}
	
	public java.math.BigDecimal getCash() {
		return get("cash");
	}

	public M setPostage(java.lang.Integer postage) {
		set("postage", postage);
		return (M)this;
	}
	
	public java.lang.Integer getPostage() {
		return getInt("postage");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
