package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMarketcodeJifen<M extends BaseMarketcodeJifen<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setCodeactiveId(java.lang.Long codeactiveId) {
		set("codeactive_id", codeactiveId);
		return (M)this;
	}
	
	public java.lang.Long getCodeactiveId() {
		return getLong("codeactive_id");
	}

	public M setJifenType(java.lang.Integer jifenType) {
		set("jifen_type", jifenType);
		return (M)this;
	}
	
	public java.lang.Integer getJifenType() {
		return getInt("jifen_type");
	}

	public M setJifenNum(java.lang.Integer jifenNum) {
		set("jifen_num", jifenNum);
		return (M)this;
	}
	
	public java.lang.Integer getJifenNum() {
		return getInt("jifen_num");
	}

	public M setMaxJifenNum(java.lang.Integer maxJifenNum) {
		set("max_jifen_num", maxJifenNum);
		return (M)this;
	}
	
	public java.lang.Integer getMaxJifenNum() {
		return getInt("max_jifen_num");
	}

	public M setMinJifenNum(java.lang.Integer minJifenNum) {
		set("min_jifen_num", minJifenNum);
		return (M)this;
	}
	
	public java.lang.Integer getMinJifenNum() {
		return getInt("min_jifen_num");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

}
