package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMarketcodeCodeactive<M extends BaseMarketcodeCodeactive<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setAppId(java.lang.Long appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.Long getAppId() {
		return getLong("app_id");
	}

	public M setApplicationId(java.lang.String applicationId) {
		set("application_id", applicationId);
		return (M)this;
	}
	
	public java.lang.String getApplicationId() {
		return getStr("application_id");
	}

	public M setActivityName(java.lang.String activityName) {
		set("activity_name", activityName);
		return (M)this;
	}
	
	public java.lang.String getActivityName() {
		return getStr("activity_name");
	}

	public M setProductBrand(java.lang.String productBrand) {
		set("product_brand", productBrand);
		return (M)this;
	}
	
	public java.lang.String getProductBrand() {
		return getStr("product_brand");
	}

	public M setProductTitle(java.lang.String productTitle) {
		set("product_title", productTitle);
		return (M)this;
	}
	
	public java.lang.String getProductTitle() {
		return getStr("product_title");
	}

	public M setProductCode(java.lang.String productCode) {
		set("product_code", productCode);
		return (M)this;
	}
	
	public java.lang.String getProductCode() {
		return getStr("product_code");
	}

	public M setWxaAppid(java.lang.String wxaAppid) {
		set("wxa_appid", wxaAppid);
		return (M)this;
	}
	
	public java.lang.String getWxaAppid() {
		return getStr("wxa_appid");
	}

	public M setWxaPath(java.lang.String wxaPath) {
		set("wxa_path", wxaPath);
		return (M)this;
	}
	
	public java.lang.String getWxaPath() {
		return getStr("wxa_path");
	}

	public M setWxaType(java.lang.Integer wxaType) {
		set("wxa_type", wxaType);
		return (M)this;
	}
	
	public java.lang.Integer getWxaType() {
		return getInt("wxa_type");
	}

	public M setCodeStart(java.lang.Integer codeStart) {
		set("code_start", codeStart);
		return (M)this;
	}
	
	public java.lang.Integer getCodeStart() {
		return getInt("code_start");
	}

	public M setCodeEnd(java.lang.Integer codeEnd) {
		set("code_end", codeEnd);
		return (M)this;
	}
	
	public java.lang.Integer getCodeEnd() {
		return getInt("code_end");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
