package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMarketcodeScanrcd<M extends BaseMarketcodeScanrcd<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setIsvApplicationId(java.lang.String isvApplicationId) {
		set("isv_application_id", isvApplicationId);
		return (M)this;
	}
	
	public java.lang.String getIsvApplicationId() {
		return getStr("isv_application_id");
	}

	public M setApplicationId(java.lang.String applicationId) {
		set("application_id", applicationId);
		return (M)this;
	}
	
	public java.lang.String getApplicationId() {
		return getStr("application_id");
	}

	public M setWxaAppid(java.lang.String wxaAppid) {
		set("wxa_appid", wxaAppid);
		return (M)this;
	}
	
	public java.lang.String getWxaAppid() {
		return getStr("wxa_appid");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public M setOpenid(java.lang.String openid) {
		set("openid", openid);
		return (M)this;
	}
	
	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
