package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCard<M extends BaseCard<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setAuthUserId(java.lang.Long authUserId) {
		set("auth_user_id", authUserId);
		return (M)this;
	}
	
	public java.lang.Long getAuthUserId() {
		return getLong("auth_user_id");
	}

	public M setCardId(java.lang.String cardId) {
		set("card_id", cardId);
		return (M)this;
	}
	
	public java.lang.String getCardId() {
		return getStr("card_id");
	}

	public M setCardType(java.lang.String cardType) {
		set("card_type", cardType);
		return (M)this;
	}
	
	public java.lang.String getCardType() {
		return getStr("card_type");
	}

	public M setDealDetail(java.lang.String dealDetail) {
		set("deal_detail", dealDetail);
		return (M)this;
	}
	
	public java.lang.String getDealDetail() {
		return getStr("deal_detail");
	}

	public M setDiscount(java.lang.Integer discount) {
		set("discount", discount);
		return (M)this;
	}
	
	public java.lang.Integer getDiscount() {
		return getInt("discount");
	}

	public M setGift(java.lang.String gift) {
		set("gift", gift);
		return (M)this;
	}
	
	public java.lang.String getGift() {
		return getStr("gift");
	}

	public M setLeastCost(java.math.BigDecimal leastCost) {
		set("least_cost", leastCost);
		return (M)this;
	}
	
	public java.math.BigDecimal getLeastCost() {
		return get("least_cost");
	}

	public M setReduceCost(java.math.BigDecimal reduceCost) {
		set("reduce_cost", reduceCost);
		return (M)this;
	}
	
	public java.math.BigDecimal getReduceCost() {
		return get("reduce_cost");
	}

	public M setBackgroundPicUrl(java.lang.String backgroundPicUrl) {
		set("background_pic_url", backgroundPicUrl);
		return (M)this;
	}
	
	public java.lang.String getBackgroundPicUrl() {
		return getStr("background_pic_url");
	}

	public M setBaseInfo(java.lang.String baseInfo) {
		set("base_info", baseInfo);
		return (M)this;
	}
	
	public java.lang.String getBaseInfo() {
		return getStr("base_info");
	}

	public M setAutoActivate(java.lang.String autoActivate) {
		set("auto_activate", autoActivate);
		return (M)this;
	}
	
	public java.lang.String getAutoActivate() {
		return getStr("auto_activate");
	}

	public M setWxActivate(java.lang.String wxActivate) {
		set("wx_activate", wxActivate);
		return (M)this;
	}
	
	public java.lang.String getWxActivate() {
		return getStr("wx_activate");
	}

	public M setActivateUrl(java.lang.String activateUrl) {
		set("activate_url", activateUrl);
		return (M)this;
	}
	
	public java.lang.String getActivateUrl() {
		return getStr("activate_url");
	}

	public M setSupplyBalance(java.lang.String supplyBalance) {
		set("supply_balance", supplyBalance);
		return (M)this;
	}
	
	public java.lang.String getSupplyBalance() {
		return getStr("supply_balance");
	}

	public M setSupplyBuy(java.lang.String supplyBuy) {
		set("supply_buy", supplyBuy);
		return (M)this;
	}
	
	public java.lang.String getSupplyBuy() {
		return getStr("supply_buy");
	}

	public M setSupplyBonus(java.lang.String supplyBonus) {
		set("supply_bonus", supplyBonus);
		return (M)this;
	}
	
	public java.lang.String getSupplyBonus() {
		return getStr("supply_bonus");
	}

	public M setBonusCleared(java.lang.String bonusCleared) {
		set("bonus_cleared", bonusCleared);
		return (M)this;
	}
	
	public java.lang.String getBonusCleared() {
		return getStr("bonus_cleared");
	}

	public M setBonusRules(java.lang.String bonusRules) {
		set("bonus_rules", bonusRules);
		return (M)this;
	}
	
	public java.lang.String getBonusRules() {
		return getStr("bonus_rules");
	}

	public M setBalanceRules(java.lang.String balanceRules) {
		set("balance_rules", balanceRules);
		return (M)this;
	}
	
	public java.lang.String getBalanceRules() {
		return getStr("balance_rules");
	}

	public M setPrerogative(java.lang.String prerogative) {
		set("prerogative", prerogative);
		return (M)this;
	}
	
	public java.lang.String getPrerogative() {
		return getStr("prerogative");
	}

	public M setBindOldCardUrl(java.lang.String bindOldCardUrl) {
		set("bind_old_card_url", bindOldCardUrl);
		return (M)this;
	}
	
	public java.lang.String getBindOldCardUrl() {
		return getStr("bind_old_card_url");
	}

	public M setNeedPushOnView(java.lang.String needPushOnView) {
		set("need_push_on_view", needPushOnView);
		return (M)this;
	}
	
	public java.lang.String getNeedPushOnView() {
		return getStr("need_push_on_view");
	}

	public M setAdvancedInfo(java.lang.String advancedInfo) {
		set("advanced_info", advancedInfo);
		return (M)this;
	}
	
	public java.lang.String getAdvancedInfo() {
		return getStr("advanced_info");
	}

	public M setFrom(java.lang.String from) {
		set("from", from);
		return (M)this;
	}
	
	public java.lang.String getFrom() {
		return getStr("from");
	}

	public M setTo(java.lang.String to) {
		set("to", to);
		return (M)this;
	}
	
	public java.lang.String getTo() {
		return getStr("to");
	}

	public M setFlight(java.lang.String flight) {
		set("flight", flight);
		return (M)this;
	}
	
	public java.lang.String getFlight() {
		return getStr("flight");
	}

	public M setDepartureTime(java.util.Date departureTime) {
		set("departure_time", departureTime);
		return (M)this;
	}
	
	public java.util.Date getDepartureTime() {
		return get("departure_time");
	}

	public M setLandingTime(java.util.Date landingTime) {
		set("landing_time", landingTime);
		return (M)this;
	}
	
	public java.util.Date getLandingTime() {
		return get("landing_time");
	}

	public M setCheckInUrl(java.lang.String checkInUrl) {
		set("check_in_url", checkInUrl);
		return (M)this;
	}
	
	public java.lang.String getCheckInUrl() {
		return getStr("check_in_url");
	}

	public M setGate(java.lang.String gate) {
		set("gate", gate);
		return (M)this;
	}
	
	public java.lang.String getGate() {
		return getStr("gate");
	}

	public M setBoardingTime(java.util.Date boardingTime) {
		set("boarding_time", boardingTime);
		return (M)this;
	}
	
	public java.util.Date getBoardingTime() {
		return get("boarding_time");
	}

	public M setMeetingDetail(java.lang.String meetingDetail) {
		set("meeting_detail", meetingDetail);
		return (M)this;
	}
	
	public java.lang.String getMeetingDetail() {
		return getStr("meeting_detail");
	}

	public M setMapUrl(java.lang.String mapUrl) {
		set("map_url", mapUrl);
		return (M)this;
	}
	
	public java.lang.String getMapUrl() {
		return getStr("map_url");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
