package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseFollowConfig;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_follow_config", primaryKey = "id")
public class FollowConfig extends BaseFollowConfig<FollowConfig> {
	public static final String table = "t_follow_config";
	public static final FollowConfig dao = new FollowConfig().dao();
}
