package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseFollowReplyNews;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_follow_reply_news", primaryKey = "id")
public class FollowReplyNews extends BaseFollowReplyNews<FollowReplyNews> {
	public static final String table = "t_follow_reply_news";
	public static final FollowReplyNews dao = new FollowReplyNews().dao();
}
