package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseFollowReplyConfig;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_follow_reply_config", primaryKey = "id")
public class FollowReplyConfig extends BaseFollowReplyConfig<FollowReplyConfig> {
	public static final String table = "t_follow_reply_config";
	public static final FollowReplyConfig dao = new FollowReplyConfig().dao();
}
