package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseKeywordsReplyConfig;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_keywords_reply_config", primaryKey = "id")
public class KeywordsReplyConfig extends BaseKeywordsReplyConfig<KeywordsReplyConfig> {
	public static final String table = "t_keywords_reply_config";
	public static final KeywordsReplyConfig dao = new KeywordsReplyConfig().dao();
}
