package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseMenuReplyRcd;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_menu_reply_rcd", primaryKey = "id")
public class MenuReplyRcd extends BaseMenuReplyRcd<MenuReplyRcd> {
	public static final String table = "t_menu_reply_rcd";
}
