package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseMenuNotifyRule;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_menu_notify_rule", primaryKey = "id")
public class MenuNotifyRule extends BaseMenuNotifyRule<MenuNotifyRule> {
	public static final String table = "t_menu_notify_rule";
}
