package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseMenuNotifyConfig;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_menu_notify_config", primaryKey = "id")
public class MenuNotifyConfig extends BaseMenuNotifyConfig<MenuNotifyConfig> {
	public static final String table = "t_menu_notify_config";
}
