package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseMenuEvent;
import io.jboot.db.annotation.Table;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_menu_event", primaryKey = "id")
public class MenuEvent extends BaseMenuEvent<MenuEvent> {
	public static final String table = "t_menu_event";
}
