package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseMenuReplyNews;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_menu_reply_news", primaryKey = "id")
public class MenuReplyNews extends BaseMenuReplyNews<MenuReplyNews> {
	public static final String table = "t_menu_reply_news";
}
