package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseMenuReplyConfig;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_menu_reply_config", primaryKey = "id")
public class MenuReplyConfig extends BaseMenuReplyConfig<MenuReplyConfig> {
	public static final String table = "t_menu_reply_config";
}
