package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseNotifyer;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_notifyer", primaryKey = "id")
public class Notifyer extends BaseNotifyer<Notifyer> {
	public static final String table = "t_notifyer";
}
