package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseOrderNotifyer;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_order_notifyer", primaryKey = "id")
public class OrderNotifyer extends BaseOrderNotifyer<OrderNotifyer> {
	public static final String table = "t_order_notifyer";
	public static final OrderNotifyer dao = new OrderNotifyer().dao();
}
