package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseOrderNotifyConfig;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_order_notify_config", primaryKey = "id")
public class OrderNotifyConfig extends BaseOrderNotifyConfig<OrderNotifyConfig> {
	public static final String table = "t_order_notify_config";
	public static final OrderNotifyConfig dao = new OrderNotifyConfig().dao();
}
