package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseProductNotifyConfig;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_product_notify_config", primaryKey = "id")
public class ProductNotifyConfig extends BaseProductNotifyConfig<ProductNotifyConfig> {
	public static final String table = "t_product_notify_config";
	public static final ProductNotifyConfig dao = new ProductNotifyConfig().dao();
}
