package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseProductNotifyer;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_product_notifyer", primaryKey = "id")
public class ProductNotifyer extends BaseProductNotifyer<ProductNotifyer> {
	public static final String table = "t_product_notifyer";
	public static final ProductNotifyer dao = new ProductNotifyer().dao();
}
