package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseMultiGroup;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_multi_group", primaryKey = "id")
public class MultiGroup extends BaseMultiGroup<MultiGroup> {
	public static final String table = "t_multi_group";
	public static final MultiGroup dao = new MultiGroup().dao();
}
