package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseMultiGroupSet;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_multi_group_set", primaryKey = "id")
public class MultiGroupSet extends BaseMultiGroupSet<MultiGroupSet> {
	public static final String table = "t_multi_group_set";
	public static final MultiGroupSet dao = new MultiGroupSet().dao();
}
