package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseOrderGroup;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_order_group", primaryKey = "id")
public class OrderGroup extends BaseOrderGroup<OrderGroup> {
	public static final String table = "t_order_group";
	public static final OrderGroup dao = new OrderGroup().dao();
}
