package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseOrderGuser;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_order_guser", primaryKey = "id")
public class OrderGuser extends BaseOrderGuser<OrderGuser> {
	public static final String table = "t_order_guser";
	public static final OrderGuser dao = new OrderGuser().dao();
}
