package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseFullCutProduct;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_full_cut_product", primaryKey = "id")
public class FullCutProduct extends BaseFullCutProduct<FullCutProduct> {
	public static final String table = "t_full_cut_product";
	public static final FullCutProduct dao = new FullCutProduct().dao();
}
