package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseFullCut;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_full_cut", primaryKey = "id")
public class FullCut extends BaseFullCut<FullCut> {
	public static final String table = "t_full_cut";
	public static final FullCut dao = new FullCut().dao();
}
