package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNotifyer<M extends BaseNotifyer<M>> extends WxmModel<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("id");
	}

	public M setAppId(Long appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public Long getAppId() {
		return getLong("app_id");
	}

	public M setOpenid(String openid) {
		set("openid", openid);
		return (M)this;
	}
	
	public String getOpenid() {
		return getStr("openid");
	}

	public M setNickname(String nickname) {
		set("nickname", nickname);
		return (M)this;
	}
	
	public String getNickname() {
		return getStr("nickname");
	}

	public M setHeadimgurl(String headimgurl) {
		set("headimgurl", headimgurl);
		return (M)this;
	}
	
	public String getHeadimgurl() {
		return getStr("headimgurl");
	}

	public M setActive(Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
