package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseKeywords<M extends BaseKeywords<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setAppId(java.lang.Long appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.Long getAppId() {
		return getLong("app_id");
	}

	public M setEnableKeywords(java.lang.Boolean enableKeywords) {
		set("enable_keywords", enableKeywords);
		return (M)this;
	}
	
	public java.lang.Boolean getEnableKeywords() {
		return get("enable_keywords");
	}

	public M setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
		return (M)this;
	}
	
	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	public M setAutoTagId(java.lang.Integer autoTagId) {
		set("auto_tag_id", autoTagId);
		return (M)this;
	}
	
	public java.lang.Integer getAutoTagId() {
		return getInt("auto_tag_id");
	}

	public M setCancelTagId(java.lang.Integer cancelTagId) {
		set("cancel_tag_id", cancelTagId);
		return (M)this;
	}
	
	public java.lang.Integer getCancelTagId() {
		return getInt("cancel_tag_id");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

}
