package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseCart;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_cart", primaryKey = "id")
public class Cart extends BaseCart<Cart> {
	public static final String table = "t_cart";
	public static final Cart dao = new Cart().dao();
}
