package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseDeliveryTemplate;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_delivery_template", primaryKey = "id")
public class DeliveryTemplate extends BaseDeliveryTemplate<DeliveryTemplate> {
	public static final String table = "t_delivery_template";
	public static final DeliveryTemplate dao = new DeliveryTemplate().dao();
}
