package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseDeliverySet;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_delivery_set", primaryKey = "id")
public class DeliverySet extends BaseDeliverySet<DeliverySet> {
	public static final String table = "t_delivery_set";
	public static final DeliverySet dao = new DeliverySet().dao();
}
