package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseProductGroup;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_product_group", primaryKey = "id")
public class ProductGroup extends BaseProductGroup<ProductGroup> {
	public static final String table = "t_product_group";
	public static final ProductGroup dao = new ProductGroup().dao();
}
