package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseProductCategory;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_product_category", primaryKey = "id")
public class ProductCategory extends BaseProductCategory<ProductCategory> {
	public static final String table = "t_product_category";
	public static final ProductCategory dao = new ProductCategory().dao();
}
