package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseProduct;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_product", primaryKey = "id")
public class Product extends BaseProduct<Product> {
	public static final String table = "t_product";
	public static final Product dao = new Product().dao();
}
