package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseProductSpecValue;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_product_spec_value", primaryKey = "id")
public class ProductSpecValue extends BaseProductSpecValue<ProductSpecValue> {
	public static final String table = "t_product_spec_value";
	public static final ProductSpecValue dao = new ProductSpecValue().dao();
}
