package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseProductSpec;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_product_spec", primaryKey = "id")
public class ProductSpec extends BaseProductSpec<ProductSpec> {
	public static final String table = "t_product_spec";
	public static final ProductSpec dao = new ProductSpec().dao();
}
