package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseProductBrand;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_product_brand", primaryKey = "id")
public class ProductBrand extends BaseProductBrand<ProductBrand> {
	public static final String table = "t_product_brand";
	public static final ProductBrand dao = new ProductBrand().dao();
}
