package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseProductReview;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_product_review", primaryKey = "id")
public class ProductReview extends BaseProductReview<ProductReview> {
	public static final String table = "t_product_review";
	public static final ProductReview dao = new ProductReview().dao();
}
