package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseProductGroupSet;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_product_group_set", primaryKey = "id")
public class ProductGroupSet extends BaseProductGroupSet<ProductGroupSet> {
	public static final String table = "t_product_group_set";
	public static final ProductGroupSet dao = new ProductGroupSet().dao();
}
