package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseSpecificationValue;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_specification_value", primaryKey = "id")
public class SpecificationValue extends BaseSpecificationValue<SpecificationValue> {
	public static final String table = "t_specification_value";
	public static final SpecificationValue dao = new SpecificationValue().dao();
}
