package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseExpressTemplate;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_express_template", primaryKey = "id")
public class ExpressTemplate extends BaseExpressTemplate<ExpressTemplate> {
	public static final String table = "t_express_template";
	public static final ExpressTemplate dao = new ExpressTemplate().dao();
}
