package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseExpressComp;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_express_comp", primaryKey = "id")
public class ExpressComp extends BaseExpressComp<ExpressComp> {
	public static final String table = "t_express_comp";
	public static final ExpressComp dao = new ExpressComp().dao();
}
