package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseExpressImg;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_express_img", primaryKey = "id")
public class ExpressImg extends BaseExpressImg<ExpressImg> {
	public static final String table = "t_express_img";
	public static final ExpressImg dao = new ExpressImg().dao();
}
