package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseInvoiceTemplate;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_invoice_template", primaryKey = "id")
public class InvoiceTemplate extends BaseInvoiceTemplate<InvoiceTemplate> {
	public static final String table = "t_invoice_template";
	public static final InvoiceTemplate dao = new InvoiceTemplate().dao();
}
