package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseOrder;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_order", primaryKey = "id")
public class Order extends BaseOrder<Order> {
	public static final String table = "t_order";
	public static final Order dao = new Order().dao();
}
