package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseOrderPressRcd;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_order_press_rcd", primaryKey = "id")
public class OrderPressRcd extends BaseOrderPressRcd<OrderPressRcd> {
	public static final String table = "t_order_press_rcd";
	public static final OrderPressRcd dao = new OrderPressRcd().dao();
}
