package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseOrderItem;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_order_item", primaryKey = "id")
public class OrderItem extends BaseOrderItem<OrderItem> {
	public static final String table = "t_order_item";
	public static final OrderItem dao = new OrderItem().dao();
}
