package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCashback<M extends BaseCashback<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setAppId(java.lang.Long appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.Long getAppId() {
		return getLong("app_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
		return (M)this;
	}
	
	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}
	
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setCashbackMethod(java.lang.Integer cashbackMethod) {
		set("cashback_method", cashbackMethod);
		return (M)this;
	}
	
	public java.lang.Integer getCashbackMethod() {
		return getInt("cashback_method");
	}

	public M setCashbackStart(java.math.BigDecimal cashbackStart) {
		set("cashback_start", cashbackStart);
		return (M)this;
	}
	
	public java.math.BigDecimal getCashbackStart() {
		return get("cashback_start");
	}

	public M setCashbackEnd(java.math.BigDecimal cashbackEnd) {
		set("cashback_end", cashbackEnd);
		return (M)this;
	}
	
	public java.math.BigDecimal getCashbackEnd() {
		return get("cashback_end");
	}

	public M setCashbackLimit(java.lang.Integer cashbackLimit) {
		set("cashback_limit", cashbackLimit);
		return (M)this;
	}
	
	public java.lang.Integer getCashbackLimit() {
		return getInt("cashback_limit");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
