package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExpressTemplate<M extends BaseExpressTemplate<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setAppId(java.lang.Long appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.Long getAppId() {
		return getLong("app_id");
	}

	public M setExpName(java.lang.String expName) {
		set("exp_name", expName);
		return (M)this;
	}
	
	public java.lang.String getExpName() {
		return getStr("exp_name");
	}

	public M setExpKey(java.lang.String expKey) {
		set("exp_key", expKey);
		return (M)this;
	}
	
	public java.lang.String getExpKey() {
		return getStr("exp_key");
	}

	public M setExpTplcontent(java.lang.String expTplcontent) {
		set("exp_tplcontent", expTplcontent);
		return (M)this;
	}
	
	public java.lang.String getExpTplcontent() {
		return getStr("exp_tplcontent");
	}

	public M setExpDesignhtml(java.lang.String expDesignhtml) {
		set("exp_designhtml", expDesignhtml);
		return (M)this;
	}
	
	public java.lang.String getExpDesignhtml() {
		return getStr("exp_designhtml");
	}

	public M setExpBgimg(java.lang.String expBgimg) {
		set("exp_bgimg", expBgimg);
		return (M)this;
	}
	
	public java.lang.String getExpBgimg() {
		return getStr("exp_bgimg");
	}

	public M setIsDefault(java.lang.Integer isDefault) {
		set("is_default", isDefault);
		return (M)this;
	}
	
	public java.lang.Integer getIsDefault() {
		return getInt("is_default");
	}

	public M setPagewidth(java.lang.Integer pagewidth) {
		set("pagewidth", pagewidth);
		return (M)this;
	}
	
	public java.lang.Integer getPagewidth() {
		return getInt("pagewidth");
	}

	public M setPageheight(java.lang.Integer pageheight) {
		set("pageheight", pageheight);
		return (M)this;
	}
	
	public java.lang.Integer getPageheight() {
		return getInt("pageheight");
	}

	public M setOffsetx(java.lang.Integer offsetx) {
		set("offsetx", offsetx);
		return (M)this;
	}
	
	public java.lang.Integer getOffsetx() {
		return getInt("offsetx");
	}

	public M setOffsety(java.lang.Integer offsety) {
		set("offsety", offsety);
		return (M)this;
	}
	
	public java.lang.Integer getOffsety() {
		return getInt("offsety");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Integer getActive() {
		return getInt("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
