package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInvoiceTemplate<M extends BaseInvoiceTemplate<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setAppId(java.lang.Long appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.Long getAppId() {
		return getLong("app_id");
	}

	public M setInvTplcontent(java.lang.String invTplcontent) {
		set("inv_tplcontent", invTplcontent);
		return (M)this;
	}
	
	public java.lang.String getInvTplcontent() {
		return getStr("inv_tplcontent");
	}

	public M setInvDesignhtml(java.lang.String invDesignhtml) {
		set("inv_designhtml", invDesignhtml);
		return (M)this;
	}
	
	public java.lang.String getInvDesignhtml() {
		return getStr("inv_designhtml");
	}

	public M setInvTabelhtml(java.lang.String invTabelhtml) {
		set("inv_tabelhtml", invTabelhtml);
		return (M)this;
	}
	
	public java.lang.String getInvTabelhtml() {
		return getStr("inv_tabelhtml");
	}

	public M setInvImgDesignhtml(java.lang.String invImgDesignhtml) {
		set("inv_img_designhtml", invImgDesignhtml);
		return (M)this;
	}
	
	public java.lang.String getInvImgDesignhtml() {
		return getStr("inv_img_designhtml");
	}

	public M setPagewidth(java.lang.Integer pagewidth) {
		set("pagewidth", pagewidth);
		return (M)this;
	}
	
	public java.lang.Integer getPagewidth() {
		return getInt("pagewidth");
	}

	public M setPageheight(java.lang.Integer pageheight) {
		set("pageheight", pageheight);
		return (M)this;
	}
	
	public java.lang.Integer getPageheight() {
		return getInt("pageheight");
	}

	public M setOffsetx(java.lang.Integer offsetx) {
		set("offsetx", offsetx);
		return (M)this;
	}
	
	public java.lang.Integer getOffsetx() {
		return getInt("offsetx");
	}

	public M setOffsety(java.lang.Integer offsety) {
		set("offsety", offsety);
		return (M)this;
	}
	
	public java.lang.Integer getOffsety() {
		return getInt("offsety");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Integer getActive() {
		return getInt("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
