package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAuthUser<M extends BaseAuthUser<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}
	
	public java.lang.Long getSellerId() {
		return getLong("seller_id");
	}

	public M setAppId(java.lang.String appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.String getAppId() {
		return getStr("app_id");
	}

	public M setAuthorizerAccessToken(java.lang.String authorizerAccessToken) {
		set("authorizer_access_token", authorizerAccessToken);
		return (M)this;
	}
	
	public java.lang.String getAuthorizerAccessToken() {
		return getStr("authorizer_access_token");
	}

	public M setAuthorizerRefreshToken(java.lang.String authorizerRefreshToken) {
		set("authorizer_refresh_token", authorizerRefreshToken);
		return (M)this;
	}
	
	public java.lang.String getAuthorizerRefreshToken() {
		return getStr("authorizer_refresh_token");
	}

	public M setExpiresIn(java.lang.Integer expiresIn) {
		set("expires_in", expiresIn);
		return (M)this;
	}
	
	public java.lang.Integer getExpiresIn() {
		return getInt("expires_in");
	}

	public M setSelectFuncInfo(java.lang.String selectFuncInfo) {
		set("select_func_info", selectFuncInfo);
		return (M)this;
	}
	
	public java.lang.String getSelectFuncInfo() {
		return getStr("select_func_info");
	}

	public M setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
		return (M)this;
	}
	
	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	public M setHeadImg(java.lang.String headImg) {
		set("head_img", headImg);
		return (M)this;
	}
	
	public java.lang.String getHeadImg() {
		return getStr("head_img");
	}

	public M setServiceTypeInfo(java.lang.String serviceTypeInfo) {
		set("service_type_info", serviceTypeInfo);
		return (M)this;
	}
	
	public java.lang.String getServiceTypeInfo() {
		return getStr("service_type_info");
	}

	public M setVerifyTypeInfo(java.lang.String verifyTypeInfo) {
		set("verify_type_info", verifyTypeInfo);
		return (M)this;
	}
	
	public java.lang.String getVerifyTypeInfo() {
		return getStr("verify_type_info");
	}

	public M setServiceType(java.lang.Integer serviceType) {
		set("service_type", serviceType);
		return (M)this;
	}
	
	public java.lang.Integer getServiceType() {
		return getInt("service_type");
	}

	public M setVerifyType(java.lang.Integer verifyType) {
		set("verify_type", verifyType);
		return (M)this;
	}
	
	public java.lang.Integer getVerifyType() {
		return getInt("verify_type");
	}

	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	public M setPrincipalName(java.lang.String principalName) {
		set("principal_name", principalName);
		return (M)this;
	}
	
	public java.lang.String getPrincipalName() {
		return getStr("principal_name");
	}

	public M setBusinessInfo(java.lang.String businessInfo) {
		set("business_info", businessInfo);
		return (M)this;
	}
	
	public java.lang.String getBusinessInfo() {
		return getStr("business_info");
	}

	public M setAlias(java.lang.String alias) {
		set("alias", alias);
		return (M)this;
	}
	
	public java.lang.String getAlias() {
		return getStr("alias");
	}

	public M setQrcodeUrl(java.lang.String qrcodeUrl) {
		set("qrcode_url", qrcodeUrl);
		return (M)this;
	}
	
	public java.lang.String getQrcodeUrl() {
		return getStr("qrcode_url");
	}

	public M setFuncInfo(java.lang.String funcInfo) {
		set("func_info", funcInfo);
		return (M)this;
	}
	
	public java.lang.String getFuncInfo() {
		return getStr("func_info");
	}

	public M setIsUsed(java.lang.Boolean isUsed) {
		set("is_used", isUsed);
		return (M)this;
	}
	
	public java.lang.Boolean getIsUsed() {
		return get("is_used");
	}

	public M setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
		return (M)this;
	}
	
	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public M setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
		return (M)this;
	}
	
	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setFansCount(java.lang.Integer fansCount) {
		set("fans_count", fansCount);
		return (M)this;
	}
	
	public java.lang.Integer getFansCount() {
		return getInt("fans_count");
	}

	public M setAddFansCount(java.lang.Integer addFansCount) {
		set("add_fans_count", addFansCount);
		return (M)this;
	}
	
	public java.lang.Integer getAddFansCount() {
		return getInt("add_fans_count");
	}

	public M setItaFansCount(java.lang.Integer itaFansCount) {
		set("ita_fans_count", itaFansCount);
		return (M)this;
	}
	
	public java.lang.Integer getItaFansCount() {
		return getInt("ita_fans_count");
	}

	public M setDelFansCount(java.lang.Integer delFansCount) {
		set("del_fans_count", delFansCount);
		return (M)this;
	}
	
	public java.lang.Integer getDelFansCount() {
		return getInt("del_fans_count");
	}

	public M setMiniprograminfo(java.lang.String miniprograminfo) {
		set("miniprograminfo", miniprograminfo);
		return (M)this;
	}
	
	public java.lang.String getMiniprograminfo() {
		return getStr("miniprograminfo");
	}

	public M setRefreshTime(java.util.Date refreshTime) {
		set("refresh_time", refreshTime);
		return (M)this;
	}
	
	public java.util.Date getRefreshTime() {
		return get("refresh_time");
	}

	public M setMarketcodeKey(java.lang.String marketcodeKey) {
		set("marketcode_key", marketcodeKey);
		return (M)this;
	}
	
	public java.lang.String getMarketcodeKey() {
		return getStr("marketcode_key");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Integer getActive() {
		return getInt("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
