package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePurchaseOrder<M extends BasePurchaseOrder<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setUserId(java.lang.Long userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public M setPurchaseId(java.lang.Long purchaseId) {
		set("purchase_id", purchaseId);
		return (M)this;
	}
	
	public java.lang.Long getPurchaseId() {
		return getLong("purchase_id");
	}

	public M setAppId(java.lang.Long appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.Long getAppId() {
		return getLong("app_id");
	}

	public M setOrderSn(java.lang.String orderSn) {
		set("order_sn", orderSn);
		return (M)this;
	}
	
	public java.lang.String getOrderSn() {
		return getStr("order_sn");
	}

	public M setTradeNo(java.lang.String tradeNo) {
		set("trade_no", tradeNo);
		return (M)this;
	}
	
	public java.lang.String getTradeNo() {
		return getStr("trade_no");
	}

	public M setAlipayTradeNo(java.lang.String alipayTradeNo) {
		set("alipay_trade_no", alipayTradeNo);
		return (M)this;
	}
	
	public java.lang.String getAlipayTradeNo() {
		return getStr("alipay_trade_no");
	}

	public M setPayFee(java.lang.Double payFee) {
		set("pay_fee", payFee);
		return (M)this;
	}
	
	public java.lang.Double getPayFee() {
		return getDouble("pay_fee");
	}

	public M setPayType(java.lang.String payType) {
		set("pay_type", payType);
		return (M)this;
	}
	
	public java.lang.String getPayType() {
		return getStr("pay_type");
	}

	public M setMemo(java.lang.String memo) {
		set("memo", memo);
		return (M)this;
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Integer getActive() {
		return getInt("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
