package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMultiGroup<M extends BaseMultiGroup<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setAppId(java.lang.Long appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.Long getAppId() {
		return getLong("app_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setOfferNum(java.lang.Integer offerNum) {
		set("offer_num", offerNum);
		return (M)this;
	}
	
	public java.lang.Integer getOfferNum() {
		return getInt("offer_num");
	}

	public M setQuota(java.lang.Integer quota) {
		set("quota", quota);
		return (M)this;
	}
	
	public java.lang.Integer getQuota() {
		return getInt("quota");
	}

	public M setValidTime(java.lang.Integer validTime) {
		set("valid_time", validTime);
		return (M)this;
	}
	
	public java.lang.Integer getValidTime() {
		return getInt("valid_time");
	}

	public M setEnableMoniSuc(java.lang.Boolean enableMoniSuc) {
		set("enable_moni_suc", enableMoniSuc);
		return (M)this;
	}
	
	public java.lang.Boolean getEnableMoniSuc() {
		return get("enable_moni_suc");
	}

	public M setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
		return (M)this;
	}
	
	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public M setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
		return (M)this;
	}
	
	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public M setMultiType(java.lang.Integer multiType) {
		set("multi_type", multiType);
		return (M)this;
	}
	
	public java.lang.Integer getMultiType() {
		return getInt("multi_type");
	}

	public M setGroupCondition(java.lang.Integer groupCondition) {
		set("group_condition", groupCondition);
		return (M)this;
	}
	
	public java.lang.Integer getGroupCondition() {
		return getInt("group_condition");
	}

	public M setNeedFollows(java.lang.Boolean needFollows) {
		set("need_follows", needFollows);
		return (M)this;
	}
	
	public java.lang.Boolean getNeedFollows() {
		return get("need_follows");
	}

	public M setFollowsTitle(java.lang.String followsTitle) {
		set("follows_title", followsTitle);
		return (M)this;
	}
	
	public java.lang.String getFollowsTitle() {
		return getStr("follows_title");
	}

	public M setFollowsImage(java.lang.String followsImage) {
		set("follows_image", followsImage);
		return (M)this;
	}
	
	public java.lang.String getFollowsImage() {
		return getStr("follows_image");
	}

	public M setFollowsIntro(java.lang.String followsIntro) {
		set("follows_intro", followsIntro);
		return (M)this;
	}
	
	public java.lang.String getFollowsIntro() {
		return getStr("follows_intro");
	}

	public M setActivityImage(java.lang.String activityImage) {
		set("activity_image", activityImage);
		return (M)this;
	}
	
	public java.lang.String getActivityImage() {
		return getStr("activity_image");
	}

	public M setActivityExplain(java.lang.String activityExplain) {
		set("activity_explain", activityExplain);
		return (M)this;
	}
	
	public java.lang.String getActivityExplain() {
		return getStr("activity_explain");
	}

	public M setShareImage(java.lang.String shareImage) {
		set("share_image", shareImage);
		return (M)this;
	}
	
	public java.lang.String getShareImage() {
		return getStr("share_image");
	}

	public M setShareTitle(java.lang.String shareTitle) {
		set("share_title", shareTitle);
		return (M)this;
	}
	
	public java.lang.String getShareTitle() {
		return getStr("share_title");
	}

	public M setShareIntro(java.lang.String shareIntro) {
		set("share_intro", shareIntro);
		return (M)this;
	}
	
	public java.lang.String getShareIntro() {
		return getStr("share_intro");
	}

	public M setDetailTitle(java.lang.String detailTitle) {
		set("detail_title", detailTitle);
		return (M)this;
	}
	
	public java.lang.String getDetailTitle() {
		return getStr("detail_title");
	}

	public M setDetailIntro(java.lang.String detailIntro) {
		set("detail_intro", detailIntro);
		return (M)this;
	}
	
	public java.lang.String getDetailIntro() {
		return getStr("detail_intro");
	}

	public M setFollowsUrl(java.lang.String followsUrl) {
		set("follows_url", followsUrl);
		return (M)this;
	}
	
	public java.lang.String getFollowsUrl() {
		return getStr("follows_url");
	}

	public M setFollowsTicket(java.lang.String followsTicket) {
		set("follows_ticket", followsTicket);
		return (M)this;
	}
	
	public java.lang.String getFollowsTicket() {
		return getStr("follows_ticket");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
