package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSellerCashRcd<M extends BaseSellerCashRcd<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}
	
	public java.lang.Long getSellerId() {
		return getLong("seller_id");
	}

	public M setWantCash(java.math.BigDecimal wantCash) {
		set("want_cash", wantCash);
		return (M)this;
	}
	
	public java.math.BigDecimal getWantCash() {
		return get("want_cash");
	}

	public M setCashType(java.lang.Integer cashType) {
		set("cash_type", cashType);
		return (M)this;
	}
	
	public java.lang.Integer getCashType() {
		return getInt("cash_type");
	}

	public M setCashAccount(java.lang.String cashAccount) {
		set("cash_account", cashAccount);
		return (M)this;
	}
	
	public java.lang.String getCashAccount() {
		return getStr("cash_account");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setMemo(java.lang.String memo) {
		set("memo", memo);
		return (M)this;
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
