package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWeappTemplate<M extends BaseWeappTemplate<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setTemplateId(java.lang.Integer templateId) {
		set("template_id", templateId);
		return (M)this;
	}
	
	public java.lang.Integer getTemplateId() {
		return getInt("template_id");
	}

	public M setTemplateName(java.lang.String templateName) {
		set("template_name", templateName);
		return (M)this;
	}
	
	public java.lang.String getTemplateName() {
		return getStr("template_name");
	}

	public M setTemplateType(java.lang.Integer templateType) {
		set("template_type", templateType);
		return (M)this;
	}
	
	public java.lang.Integer getTemplateType() {
		return getInt("template_type");
	}

	public M setVersion(java.lang.String version) {
		set("version", version);
		return (M)this;
	}
	
	public java.lang.String getVersion() {
		return getStr("version");
	}

	public M setVersionDesc(java.lang.String versionDesc) {
		set("version_desc", versionDesc);
		return (M)this;
	}
	
	public java.lang.String getVersionDesc() {
		return getStr("version_desc");
	}
	
	public M setProcessClass(java.lang.String processClass) {
		set("process_class", processClass);
		return (M)this;
	}
	
	public java.lang.String getProcessClass() {
		return getStr("process_class");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
