package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWeappStyle<M extends BaseWeappStyle<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setNavbarBgcolor(java.lang.String navbarBgcolor) {
		set("navbar_bgcolor", navbarBgcolor);
		return (M)this;
	}
	
	public java.lang.String getNavbarBgcolor() {
		return getStr("navbar_bgcolor");
	}

	public M setOtherBgcolor(java.lang.String otherBgcolor) {
		set("other_bgcolor", otherBgcolor);
		return (M)this;
	}
	
	public java.lang.String getOtherBgcolor() {
		return getStr("other_bgcolor");
	}

	public M setTabbarColor(java.lang.String tabbarColor) {
		set("tabbar_color", tabbarColor);
		return (M)this;
	}
	
	public java.lang.String getTabbarColor() {
		return getStr("tabbar_color");
	}

	public M setTabbarSelectedColor(java.lang.String tabbarSelectedColor) {
		set("tabbar_selected_color", tabbarSelectedColor);
		return (M)this;
	}
	
	public java.lang.String getTabbarSelectedColor() {
		return getStr("tabbar_selected_color");
	}

	public M setTabbarBgColor(java.lang.String tabbarBgColor) {
		set("tabbar_bg_color", tabbarBgColor);
		return (M)this;
	}
	
	public java.lang.String getTabbarBgColor() {
		return getStr("tabbar_bg_color");
	}

	public M setDisplayHtml(java.lang.String displayHtml) {
		set("display_html", displayHtml);
		return (M)this;
	}
	
	public java.lang.String getDisplayHtml() {
		return getStr("display_html");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
