package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCommissionRate<M extends BaseCommissionRate<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setAppId(java.lang.Long appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.Long getAppId() {
		return getLong("app_id");
	}

	public M setSelfUpRate(java.math.BigDecimal selfUpRate) {
		set("self_up_rate", selfUpRate);
		return (M)this;
	}
	
	public java.math.BigDecimal getSelfUpRate() {
		return get("self_up_rate");
	}

	public M setSecondUpRate(java.math.BigDecimal secondUpRate) {
		set("second_up_rate", secondUpRate);
		return (M)this;
	}
	
	public java.math.BigDecimal getSecondUpRate() {
		return get("second_up_rate");
	}

	public M setThirdUpRate(java.math.BigDecimal thirdUpRate) {
		set("third_up_rate", thirdUpRate);
		return (M)this;
	}
	
	public java.math.BigDecimal getThirdUpRate() {
		return get("third_up_rate");
	}

	public M setSelfBuyRate(java.lang.Boolean selfBuyRate) {
		set("self_buy_rate", selfBuyRate);
		return (M)this;
	}
	
	public java.lang.Boolean getSelfBuyRate() {
		return get("self_buy_rate");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
