package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAuthCert<M extends BaseAuthCert<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setAppId(java.lang.String appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.String getAppId() {
		return getStr("app_id");
	}

	public M setPayMchId(java.lang.String payMchId) {
		set("pay_mch_id", payMchId);
		return (M)this;
	}
	
	public java.lang.String getPayMchId() {
		return getStr("pay_mch_id");
	}

	public M setPaySecretKey(java.lang.String paySecretKey) {
		set("pay_secret_key", paySecretKey);
		return (M)this;
	}
	
	public java.lang.String getPaySecretKey() {
		return getStr("pay_secret_key");
	}

	public M setCertFile(byte[] certFile) {
		set("cert_file", certFile);
		return (M)this;
	}
	
	public byte[] getCertFile() {
		return get("cert_file");
	}

	public M setIsDefault(java.lang.Boolean isDefault) {
		set("is_default", isDefault);
		return (M)this;
	}
	
	public java.lang.Boolean getIsDefault() {
		return get("is_default");
	}

	public M setIsUse(java.lang.Boolean isUse) {
		set("is_use", isUse);
		return (M)this;
	}
	
	public java.lang.Boolean getIsUse() {
		return get("is_use");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Integer getActive() {
		return getInt("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
