package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWxamsgTemplate<M extends BaseWxamsgTemplate<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setAppId(java.lang.Long appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.Long getAppId() {
		return getLong("app_id");
	}

	public M setTemplateKuId(java.lang.String templateKuId) {
		set("template_ku_id", templateKuId);
		return (M)this;
	}
	
	public java.lang.String getTemplateKuId() {
		return getStr("template_ku_id");
	}

	public M setTemplateId(java.lang.String templateId) {
		set("template_id", templateId);
		return (M)this;
	}
	
	public java.lang.String getTemplateId() {
		return getStr("template_id");
	}

	public M setTemplateType(java.lang.Integer templateType) {
		set("template_type", templateType);
		return (M)this;
	}
	
	public java.lang.Integer getTemplateType() {
		return getInt("template_type");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
