package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSellerUser<M extends BaseSellerUser<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}
	
	public java.lang.Long getSellerId() {
		return getLong("seller_id");
	}

	public M setNick(java.lang.String nick) {
		set("nick", nick);
		return (M)this;
	}
	
	public java.lang.String getNick() {
		return getStr("nick");
	}

	public M setHeaderImg(java.lang.String headerImg) {
		set("header_img", headerImg);
		return (M)this;
	}
	
	public java.lang.String getHeaderImg() {
		return getStr("header_img");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setSalt(java.lang.String salt) {
		set("salt", salt);
		return (M)this;
	}
	
	public java.lang.String getSalt() {
		return getStr("salt");
	}

	public M setTradePassword(java.lang.String tradePassword) {
		set("trade_password", tradePassword);
		return (M)this;
	}
	
	public java.lang.String getTradePassword() {
		return getStr("trade_password");
	}

	public M setUserLevel(java.lang.Integer userLevel) {
		set("user_level", userLevel);
		return (M)this;
	}
	
	public java.lang.Integer getUserLevel() {
		return getInt("user_level");
	}

	public M setLoginTime(java.util.Date loginTime) {
		set("login_time", loginTime);
		return (M)this;
	}
	
	public java.util.Date getLoginTime() {
		return get("login_time");
	}

	public M setGenCodeTime(java.util.Date genCodeTime) {
		set("gen_code_time", genCodeTime);
		return (M)this;
	}
	
	public java.util.Date getGenCodeTime() {
		return get("gen_code_time");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setMyInviteCode(java.lang.String myInviteCode) {
		set("my_invite_code", myInviteCode);
		return (M)this;
	}
	
	public java.lang.String getMyInviteCode() {
		return getStr("my_invite_code");
	}

	public M setShareInviteCode(java.lang.String shareInviteCode) {
		set("share_invite_code", shareInviteCode);
		return (M)this;
	}
	
	public java.lang.String getShareInviteCode() {
		return getStr("share_invite_code");
	}

	public M setVersionNo(java.lang.Integer versionNo) {
		set("version_no", versionNo);
		return (M)this;
	}
	
	public java.lang.Integer getVersionNo() {
		return getInt("version_no");
	}

	public M setLoginIp(java.lang.String loginIp) {
		set("login_ip", loginIp);
		return (M)this;
	}
	
	public java.lang.String getLoginIp() {
		return getStr("login_ip");
	}

	public M setLoginFailureCount(java.lang.Integer loginFailureCount) {
		set("login_failure_count", loginFailureCount);
		return (M)this;
	}
	
	public java.lang.Integer getLoginFailureCount() {
		return getInt("login_failure_count");
	}

	public M setOpenId(java.lang.String openId) {
		set("open_id", openId);
		return (M)this;
	}
	
	public java.lang.String getOpenId() {
		return getStr("open_id");
	}

	public M setWeimoPid(java.lang.String weimoPid) {
		set("weimo_pid", weimoPid);
		return (M)this;
	}
	
	public java.lang.String getWeimoPid() {
		return getStr("weimo_pid");
	}

	public M setKdtId(java.lang.String kdtId) {
		set("kdt_id", kdtId);
		return (M)this;
	}
	
	public java.lang.String getKdtId() {
		return getStr("kdt_id");
	}

	public M setAccessToken(java.lang.String accessToken) {
		set("access_token", accessToken);
		return (M)this;
	}
	
	public java.lang.String getAccessToken() {
		return getStr("access_token");
	}

	public M setBalance(java.math.BigDecimal balance) {
		set("balance", balance);
		return (M)this;
	}
	
	public java.math.BigDecimal getBalance() {
		return get("balance");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Integer getActive() {
		return getInt("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
