package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAuthWeimo<M extends BaseAuthWeimo<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}
	
	public java.lang.Long getSellerId() {
		return getLong("seller_id");
	}

	public M setPid(java.lang.String pid) {
		set("pid", pid);
		return (M)this;
	}
	
	public java.lang.String getPid() {
		return getStr("pid");
	}

	public M setShopName(java.lang.String shopName) {
		set("shop_name", shopName);
		return (M)this;
	}
	
	public java.lang.String getShopName() {
		return getStr("shop_name");
	}

	public M setShopLogo(java.lang.String shopLogo) {
		set("shop_logo", shopLogo);
		return (M)this;
	}
	
	public java.lang.String getShopLogo() {
		return getStr("shop_logo");
	}

	public M setAccessToken(java.lang.String accessToken) {
		set("access_token", accessToken);
		return (M)this;
	}
	
	public java.lang.String getAccessToken() {
		return getStr("access_token");
	}

	public M setExpiresIn(java.lang.Integer expiresIn) {
		set("expires_in", expiresIn);
		return (M)this;
	}
	
	public java.lang.Integer getExpiresIn() {
		return getInt("expires_in");
	}

	public M setRefreshToken(java.lang.String refreshToken) {
		set("refresh_token", refreshToken);
		return (M)this;
	}
	
	public java.lang.String getRefreshToken() {
		return getStr("refresh_token");
	}

	public M setRefreshTokenExpiresIn(java.lang.Integer refreshTokenExpiresIn) {
		set("refresh_token_expires_in", refreshTokenExpiresIn);
		return (M)this;
	}
	
	public java.lang.Integer getRefreshTokenExpiresIn() {
		return getInt("refresh_token_expires_in");
	}

	public M setBusinessId(java.lang.String businessId) {
		set("business_id", businessId);
		return (M)this;
	}
	
	public java.lang.String getBusinessId() {
		return getStr("business_id");
	}

	public M setPublicAccountId(java.lang.String publicAccountId) {
		set("public_account_id", publicAccountId);
		return (M)this;
	}
	
	public java.lang.String getPublicAccountId() {
		return getStr("public_account_id");
	}

	public M setLoginTime(java.util.Date loginTime) {
		set("login_time", loginTime);
		return (M)this;
	}
	
	public java.util.Date getLoginTime() {
		return get("login_time");
	}

	public M setLoginIp(java.lang.String loginIp) {
		set("login_ip", loginIp);
		return (M)this;
	}
	
	public java.lang.String getLoginIp() {
		return getStr("login_ip");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Integer getActive() {
		return getInt("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
