package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSellerImages<M extends BaseSellerImages<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}
	
	public java.lang.Long getSellerId() {
		return getLong("seller_id");
	}

	public M setFileType(java.lang.Integer fileType) {
		set("file_type", fileType);
		return (M)this;
	}
	
	public java.lang.Integer getFileType() {
		return getInt("file_type");
	}

	public M setImgGroupId(java.lang.Long imgGroupId) {
		set("img_group_id", imgGroupId);
		return (M)this;
	}
	
	public java.lang.Long getImgGroupId() {
		return getLong("img_group_id");
	}

	public M setImgPath(java.lang.String imgPath) {
		set("img_path", imgPath);
		return (M)this;
	}
	
	public java.lang.String getImgPath() {
		return getStr("img_path");
	}

	public M setMediaId(java.lang.String mediaId) {
		set("media_id", mediaId);
		return (M)this;
	}
	
	public java.lang.String getMediaId() {
		return getStr("media_id");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Integer getActive() {
		return getInt("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

}
