package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMenuReplyConfig<M extends BaseMenuReplyConfig<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setAppId(java.lang.Long appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.Long getAppId() {
		return getLong("app_id");
	}

	public M setMenuKey(java.lang.String menuKey) {
		set("menu_key", menuKey);
		return (M)this;
	}
	
	public java.lang.String getMenuKey() {
		return getStr("menu_key");
	}

	public M setMsgType(java.lang.Integer msgType) {
		set("msg_type", msgType);
		return (M)this;
	}
	
	public java.lang.Integer getMsgType() {
		return getInt("msg_type");
	}

	public M setMsgTextContent(java.lang.String msgTextContent) {
		set("msg_text_content", msgTextContent);
		return (M)this;
	}
	
	public java.lang.String getMsgTextContent() {
		return getStr("msg_text_content");
	}

	public M setEventType(java.lang.Integer eventType) {
		set("event_type", eventType);
		return (M)this;
	}
	
	public java.lang.Integer getEventType() {
		return getInt("event_type");
	}

	public M setMediaId(java.lang.String mediaId) {
		set("media_id", mediaId);
		return (M)this;
	}
	
	public java.lang.String getMediaId() {
		return getStr("media_id");
	}

	public M setMediaPic(java.lang.String mediaPic) {
		set("media_pic", mediaPic);
		return (M)this;
	}
	
	public java.lang.String getMediaPic() {
		return getStr("media_pic");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
