package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMenu<M extends BaseMenu<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setAppId(java.lang.Long appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.Long getAppId() {
		return getLong("app_id");
	}

	public M setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
		return (M)this;
	}
	
	public java.lang.Long getParentId() {
		return getLong("parent_id");
	}

	public M setMenuName(java.lang.String menuName) {
		set("menu_name", menuName);
		return (M)this;
	}
	
	public java.lang.String getMenuName() {
		return getStr("menu_name");
	}

	public M setMenuUrl(java.lang.String menuUrl) {
		set("menu_url", menuUrl);
		return (M)this;
	}
	
	public java.lang.String getMenuUrl() {
		return getStr("menu_url");
	}

	public M setMenuType(java.lang.Integer menuType) {
		set("menu_type", menuType);
		return (M)this;
	}
	
	public java.lang.Integer getMenuType() {
		return getInt("menu_type");
	}

	public M setClassId(java.lang.String classId) {
		set("class_id", classId);
		return (M)this;
	}
	
	public java.lang.String getClassId() {
		return getStr("class_id");
	}

	public M setMenuIcon(java.lang.String menuIcon) {
		set("menu_icon", menuIcon);
		return (M)this;
	}
	
	public java.lang.String getMenuIcon() {
		return getStr("menu_icon");
	}

	public M setMenuOrder(java.lang.Integer menuOrder) {
		set("menu_order", menuOrder);
		return (M)this;
	}
	
	public java.lang.Integer getMenuOrder() {
		return getInt("menu_order");
	}

	public M setMenuGroup(java.lang.Integer menuGroup) {
		set("menu_group", menuGroup);
		return (M)this;
	}

	public java.lang.Integer getMenuGroup() {
		return getInt("menu_group");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
