package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWeappStyleTabbarItem<M extends BaseWeappStyleTabbarItem<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setStyleId(java.lang.Long styleId) {
		set("style_id", styleId);
		return (M)this;
	}
	
	public java.lang.Long getStyleId() {
		return getLong("style_id");
	}

	public M setTabbarIndex(java.lang.Integer tabbarIndex) {
		set("tabbar_index", tabbarIndex);
		return (M)this;
	}
	
	public java.lang.Integer getTabbarIndex() {
		return getInt("tabbar_index");
	}

	public M setTabbarTitle(java.lang.String tabbarTitle) {
		set("tabbar_title", tabbarTitle);
		return (M)this;
	}
	
	public java.lang.String getTabbarTitle() {
		return getStr("tabbar_title");
	}

	public M setTabbarIconPath(java.lang.String tabbarIconPath) {
		set("tabbar_icon_path", tabbarIconPath);
		return (M)this;
	}
	
	public java.lang.String getTabbarIconPath() {
		return getStr("tabbar_icon_path");
	}

	public M setTabbarSelectedIconpath(java.lang.String tabbarSelectedIconpath) {
		set("tabbar_selected_iconpath", tabbarSelectedIconpath);
		return (M)this;
	}
	
	public java.lang.String getTabbarSelectedIconpath() {
		return getStr("tabbar_selected_iconpath");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
