package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAuthShopOrder<M extends BaseAuthShopOrder<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setKdtId(java.lang.String kdtId) {
		set("kdt_id", kdtId);
		return (M)this;
	}
	
	public java.lang.String getKdtId() {
		return getStr("kdt_id");
	}

	public M setSkuVersion(java.lang.String skuVersion) {
		set("sku_version", skuVersion);
		return (M)this;
	}
	
	public java.lang.String getSkuVersion() {
		return getStr("sku_version");
	}

	public M setSkuInterval(java.lang.Integer skuInterval) {
		set("sku_interval", skuInterval);
		return (M)this;
	}
	
	public java.lang.Integer getSkuInterval() {
		return getInt("sku_interval");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
		return (M)this;
	}
	
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	public M setBuyerPhone(java.lang.String buyerPhone) {
		set("buyer_phone", buyerPhone);
		return (M)this;
	}
	
	public java.lang.String getBuyerPhone() {
		return getStr("buyer_phone");
	}

	public M setPayTime(java.util.Date payTime) {
		set("pay_time", payTime);
		return (M)this;
	}
	
	public java.util.Date getPayTime() {
		return get("pay_time");
	}

	public M setPrice(java.lang.String price) {
		set("price", price);
		return (M)this;
	}
	
	public java.lang.String getPrice() {
		return getStr("price");
	}

	public M setAppId(java.lang.String appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	public java.lang.String getAppId() {
		return getStr("app_id");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
