package com.dbumama.market.model.base;

import com.dbumama.market.model.gen.WxmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePromotionSet<M extends BasePromotionSet<M>> extends WxmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setPromotionId(java.lang.Long promotionId) {
		set("promotion_id", promotionId);
		return (M)this;
	}
	
	public java.lang.Long getPromotionId() {
		return getLong("promotion_id");
	}

	public M setProductId(java.lang.Long productId) {
		set("product_id", productId);
		return (M)this;
	}
	
	public java.lang.Long getProductId() {
		return getLong("product_id");
	}

	public M setPromotionType(java.lang.Integer promotionType) {
		set("promotion_type", promotionType);
		return (M)this;
	}
	
	public java.lang.Integer getPromotionType() {
		return getInt("promotion_type");
	}

	public M setPromotionSetZhekou(java.lang.Float promotionSetZhekou) {
		set("promotion_set_zhekou", promotionSetZhekou);
		return (M)this;
	}
	
	public java.lang.Float getPromotionSetZhekou() {
		return getFloat("promotion_set_zhekou");
	}

	public M setPromotionSetJianjia(java.lang.Float promotionSetJianjia) {
		set("promotion_set_jianjia", promotionSetJianjia);
		return (M)this;
	}
	
	public java.lang.Float getPromotionSetJianjia() {
		return getFloat("promotion_set_jianjia");
	}

	public M setPromotionValue(java.lang.Float promotionValue) {
		set("promotion_value", promotionValue);
		return (M)this;
	}
	
	public java.lang.Float getPromotionValue() {
		return getFloat("promotion_value");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}
	
	public java.util.Date getUpdated() {
		return get("updated");
	}

}
