package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseAuthCert;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_auth_cert", primaryKey = "id")
public class AuthCert extends BaseAuthCert<AuthCert> {
	public static final String table = "t_auth_cert";
}
