package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseAuthUserApp;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_auth_user_app", primaryKey = "id")
public class AuthUserApp extends BaseAuthUserApp<AuthUserApp> {
	public static final String table = "t_auth_user_app";
}
