package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseAuthShopOrder;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_auth_shop_order", primaryKey = "id")
public class AuthShopOrder extends BaseAuthShopOrder<AuthShopOrder> {
	public static final String table = "t_auth_shop_order";
}
