package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseAuthWeimo;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_auth_weimo", primaryKey = "id")
public class AuthWeimo extends BaseAuthWeimo<AuthWeimo> {
	public static final String table = "t_auth_weimo";
}
