package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseAuthShop;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_auth_shop", primaryKey = "id")
public class AuthShop extends BaseAuthShop<AuthShop> {
	public static final String table = "t_auth_shop";
}
