package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseAuthUserStyle;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_auth_user_style", primaryKey = "id")
public class AuthUserStyle extends BaseAuthUserStyle<AuthUserStyle> {
	public static final String table = "t_auth_user_style";
}
