package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseBuyerUser;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_buyer_user", primaryKey = "id")
public class BuyerUser extends BaseBuyerUser<BuyerUser> {
	public static final String table = "t_buyer_user";
}
