package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseBuyerRecharge;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_buyer_recharge", primaryKey = "id")
public class BuyerRecharge extends BaseBuyerRecharge<BuyerRecharge> {
	public static final String table = "t_buyer_recharge";
}
