package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseCompTicket;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_comp_ticket", primaryKey = "id")
public class CompTicket extends BaseCompTicket<CompTicket> {
	public static final String table = "t_comp_ticket";
}
