package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseEmployee;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_employee", primaryKey = "id")
public class Employee extends BaseEmployee<Employee> {
	public static final String table = "t_employee";
}
