package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseImageGroup;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_image_group", primaryKey = "id")
public class ImageGroup extends BaseImageGroup<ImageGroup> {
	public static final String table = "t_image_group";
}
