package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseImageSowing;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_image_sowing", primaryKey = "id")
public class ImageSowing extends BaseImageSowing<ImageSowing> {
	public static final String table = "t_image_sowing";
}
