package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseMenu;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_menu", primaryKey = "id")
public class Menu extends BaseMenu<Menu> {
	public static final String table = "t_menu";
}
