package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BasePayee;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_payee", primaryKey = "id")
public class Payee extends BasePayee<Payee> {
	public static final String table = "t_payee";
}
