package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BasePlatUser;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_plat_user", primaryKey = "id")
public class PlatUser extends BasePlatUser<PlatUser> {
	public static final String table = "t_plat_user";
}
