package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BasePlatActivitys;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_plat_activitys", primaryKey = "id")
public class PlatActivitys extends BasePlatActivitys<PlatActivitys> {
	public static final String table = "t_plat_activitys";
}
