package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BasePlatActivitysJoin;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_plat_activitys_join", primaryKey = "id")
public class PlatActivitysJoin extends BasePlatActivitysJoin<PlatActivitysJoin> {
	public static final String table = "t_plat_activitys_join";
}
