package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BasePlatImages;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_plat_images", primaryKey = "id")
public class PlatImages extends BasePlatImages<PlatImages> {
	public static final String table = "t_plat_images";
}
