package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BasePurchase;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_purchase", primaryKey = "id")
public class Purchase extends BasePurchase<Purchase> {
	public static final String table = "t_purchase";
}
