package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BasePurchaseOrder;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_purchase_order", primaryKey = "id")
public class PurchaseOrder extends BasePurchaseOrder<PurchaseOrder> {
	public static final String table = "t_purchase_order";
}
