package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseRolePermission;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_role_permission", primaryKey = "id")
public class RolePermission extends BaseRolePermission<RolePermission> {
	public static final String table = "t_role_permission";
}
