package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseSellerMissionRcd;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_seller_mission_rcd", primaryKey = "id")
public class SellerMissionRcd extends BaseSellerMissionRcd<SellerMissionRcd> {
	public static final String table = "t_seller_mission_rcd";
}
