package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseSelleruserBalanceRcd;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_selleruser_balance_rcd", primaryKey = "id")
public class SelleruserBalanceRcd extends BaseSelleruserBalanceRcd<SelleruserBalanceRcd> {
	public static final String table = "t_selleruser_balance_rcd";
}
