package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseSellerImages;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_seller_images", primaryKey = "id")
public class SellerImages extends BaseSellerImages<SellerImages> {
	public static final String table = "t_seller_images";
}
