package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseSellerMission;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_seller_mission", primaryKey = "id")
public class SellerMission extends BaseSellerMission<SellerMission> {
	public static final String table = "t_seller_mission";
}
