package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseSellerCashRcd;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_seller_cash_rcd", primaryKey = "id")
public class SellerCashRcd extends BaseSellerCashRcd<SellerCashRcd> {
	public static final String table = "t_seller_cash_rcd";
}
