package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseSellerAddr;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_seller_addr", primaryKey = "id")
public class SellerAddr extends BaseSellerAddr<SellerAddr> {
	public static final String table = "t_seller_addr";
}
