package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseSelleruserRechargeRcd;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_selleruser_recharge_rcd", primaryKey = "id")
public class SelleruserRechargeRcd extends BaseSelleruserRechargeRcd<SelleruserRechargeRcd> {
	public static final String table = "t_selleruser_recharge_rcd";
}
