package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseShipping;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_shipping", primaryKey = "id")
public class Shipping extends BaseShipping<Shipping> {
	public static final String table = "t_shipping";
}
