package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseShopEmployee;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_shop_employee", primaryKey = "id")
public class ShopEmployee extends BaseShopEmployee<ShopEmployee> {
	public static final String table = "t_shop_employee";
}
