package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseUserCode;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_user_code", primaryKey = "id")
public class UserCode extends BaseUserCode<UserCode> {
	public static final String table = "t_user_code";
}
