package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseWeappStyle;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_weapp_style", primaryKey = "id")
public class WeappStyle extends BaseWeappStyle<WeappStyle> {
	public static final String table = "t_weapp_style";
}
