package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseWeappTemplate;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_weapp_template", primaryKey = "id")
public class WeappTemplate extends BaseWeappTemplate<WeappTemplate> {
	public static final String table = "t_weapp_template";
}
