package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseWeappTester;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_weapp_tester", primaryKey = "id")
public class WeappTester extends BaseWeappTester<WeappTester> {
	public static final String table = "t_weapp_tester";
}
