package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseWeappStyleTabbarItem;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_weapp_style_tabbar_item", primaryKey = "id")
public class WeappStyleTabbarItem extends BaseWeappStyleTabbarItem<WeappStyleTabbarItem> {
	public static final String table = "t_weapp_style_tabbar_item";
}
