package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseWeimoApp;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_weimo_app", primaryKey = "id")
public class WeimoApp extends BaseWeimoApp<WeimoApp> {
	public static final String table = "t_weimo_app";
}
