package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseWeipageCategory;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_weipage_category", primaryKey = "id")
public class WeipageCategory extends BaseWeipageCategory<WeipageCategory> {
	public static final String table = "t_weipage_category";
}
