package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseWeiPage;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_wei_page", primaryKey = "id")
public class WeiPage extends BaseWeiPage<WeiPage> {
	public static final String table = "t_wei_page";
}
