package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseWxamsgTemplate;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_wxamsg_template", primaryKey = "id")
public class WxamsgTemplate extends BaseWxamsgTemplate<WxamsgTemplate> {
	public static final String table = "t_wxamsg_template";
}
