package com.dbumama.market.model;

import io.jboot.db.annotation.Table;
import com.dbumama.market.model.base.BaseZanTag;

/**
 * Generated by Wxmall, do not modify this file.
 * http://www.dbumama.com
 */
@SuppressWarnings("serial")
@Table(tableName = "t_zan_tag", primaryKey = "id")
public class ZanTag extends BaseZanTag<ZanTag> {
	public static final String table = "t_zan_tag";
}
